Homework #4
js-tasks-ru/js-20211109_xoroshilov pull request #5
Opened 2021-11-25 00:32 UTC by khorosh1lov

2021-11-25 00:33 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-11-25 14:02 UTC, dosandk commented on 05-dom-document-loading/1-notification/index.js
> +    this.instance = document.querySelector('div.notification');
так делать не следует, пожалуйста используйте статическое свойство

2021-11-25 14:02 UTC, dosandk commented on 05-dom-document-loading/1-notification/index.js
> +    if (wrapper) {
подумайте, поможет ли использование значение аргумента по умолчанию избавиться от `if...else`

2021-11-25 14:03 UTC, dosandk requested changes
необходимо поправить решение - использовать статическое свойство класса

2021-11-25 16:42 UTC, khorosh1lov commented
NotificationMessage was fixed, now with `static element`

2021-11-25 16:43 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-11-25 19:06 UTC, khorosh1lov commented on 05-dom-document-loading/1-notification/index.js
> +    if (wrapper) {
Fixed

2021-11-25 19:06 UTC, khorosh1lov commented on 05-dom-document-loading/1-notification/index.js
> +    this.instance = document.querySelector('div.notification');
reworked to static property

2021-11-25 19:07 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2021-11-26 10:42 UTC, dosandk approved these changes
good 👍

2021-11-26 10:43 UTC, merged